-- Baseline schema for the subscription and billing platform.
--
-- Written in portable SQL so the same migration runs on H2 (dev, tests) and PostgreSQL (prod).
-- Hibernate no longer owns the schema: ddl-auto is `none` everywhere, because `update` silently
-- mutates deployed tables on startup and can never drop or rename anything safely.

CREATE TABLE organizations (
    id         UUID         NOT NULL,
    name       VARCHAR(255) NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT pk_organizations PRIMARY KEY (id),
    CONSTRAINT uk_organizations_name UNIQUE (name)
);

CREATE TABLE plans (
    id                    BIGINT        GENERATED BY DEFAULT AS IDENTITY,
    type                  VARCHAR(32)   NOT NULL,
    monthly_price         NUMERIC(19, 4) NOT NULL,
    included_units        INTEGER       NOT NULL,
    overage_rate_per_unit NUMERIC(19, 4),
    currency              VARCHAR(3)    NOT NULL,
    CONSTRAINT pk_plans PRIMARY KEY (id),
    CONSTRAINT uk_plans_type UNIQUE (type)
);

CREATE TABLE subscriptions (
    id              UUID        NOT NULL,
    organization_id UUID        NOT NULL,
    plan_id         BIGINT      NOT NULL,
    start_date      TIMESTAMP WITH TIME ZONE NOT NULL,
    end_date        TIMESTAMP WITH TIME ZONE,
    cancelled_at    TIMESTAMP WITH TIME ZONE,
    status          VARCHAR(32) NOT NULL,
    CONSTRAINT pk_subscriptions PRIMARY KEY (id),
    CONSTRAINT fk_subscriptions_organization FOREIGN KEY (organization_id) REFERENCES organizations (id),
    CONSTRAINT fk_subscriptions_plan FOREIGN KEY (plan_id) REFERENCES plans (id)
);

CREATE INDEX idx_subscriptions_org_status ON subscriptions (organization_id, status);

CREATE TABLE usage_events (
    id              UUID    NOT NULL,
    event_id        UUID    NOT NULL,
    organization_id UUID    NOT NULL,
    units_consumed  INTEGER NOT NULL,
    occurred_at     TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT pk_usage_events PRIMARY KEY (id),
    -- Idempotency: a redelivered Kafka message cannot be counted twice.
    CONSTRAINT uk_usage_events_event_id UNIQUE (event_id),
    CONSTRAINT fk_usage_events_organization FOREIGN KEY (organization_id) REFERENCES organizations (id)
);

-- Supports the per-tenant, per-period SUM that drives invoicing.
CREATE INDEX idx_usage_events_org_time ON usage_events (organization_id, occurred_at);

CREATE TABLE processed_events (
    event_id       UUID         NOT NULL,
    consumer_group VARCHAR(128) NOT NULL,
    processed_at   TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT pk_processed_events PRIMARY KEY (event_id)
);

CREATE TABLE proration_adjustments (
    id              UUID         NOT NULL,
    organization_id UUID         NOT NULL,
    period_year     INTEGER      NOT NULL,
    period_month    INTEGER      NOT NULL,
    line_type       VARCHAR(32)  NOT NULL,
    description     VARCHAR(255) NOT NULL,
    amount          NUMERIC(19, 2) NOT NULL,
    created_at      TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT pk_proration_adjustments PRIMARY KEY (id),
    CONSTRAINT fk_proration_organization FOREIGN KEY (organization_id) REFERENCES organizations (id)
);

CREATE INDEX idx_proration_org_period
    ON proration_adjustments (organization_id, period_year, period_month);

CREATE TABLE invoices (
    id                UUID        NOT NULL,
    invoice_number    VARCHAR(64) NOT NULL,
    organization_id   UUID        NOT NULL,
    period_year       INTEGER     NOT NULL,
    period_month      INTEGER     NOT NULL,
    period_start      TIMESTAMP WITH TIME ZONE NOT NULL,
    period_end        TIMESTAMP WITH TIME ZONE NOT NULL,
    plan_type         VARCHAR(32) NOT NULL,
    included_units    INTEGER     NOT NULL,
    used_units        BIGINT      NOT NULL,
    overage_units     BIGINT      NOT NULL,
    overage_rate      NUMERIC(19, 4) NOT NULL,
    base_amount       NUMERIC(19, 2) NOT NULL,
    overage_amount    NUMERIC(19, 2) NOT NULL,
    adjustment_amount NUMERIC(19, 2) NOT NULL,
    total_amount      NUMERIC(19, 2) NOT NULL,
    currency          VARCHAR(3)  NOT NULL,
    issued_at         TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT pk_invoices PRIMARY KEY (id),
    CONSTRAINT uk_invoices_number UNIQUE (invoice_number),
    -- One invoice per tenant per period: generation is idempotent.
    CONSTRAINT uk_invoices_org_period UNIQUE (organization_id, period_year, period_month),
    CONSTRAINT fk_invoices_organization FOREIGN KEY (organization_id) REFERENCES organizations (id)
);

CREATE TABLE invoice_line_items (
    id          UUID         NOT NULL,
    invoice_id  UUID         NOT NULL,
    line_type   VARCHAR(32)  NOT NULL,
    description VARCHAR(255) NOT NULL,
    quantity    NUMERIC(19, 4) NOT NULL,
    unit_price  NUMERIC(19, 4) NOT NULL,
    amount      NUMERIC(19, 2) NOT NULL,
    CONSTRAINT pk_invoice_line_items PRIMARY KEY (id),
    CONSTRAINT fk_invoice_line_items_invoice FOREIGN KEY (invoice_id) REFERENCES invoices (id)
);

CREATE INDEX idx_invoice_line_items_invoice ON invoice_line_items (invoice_id);

CREATE TABLE quota_alerts (
    id                UUID    NOT NULL,
    organization_id   UUID    NOT NULL,
    period_year       INTEGER NOT NULL,
    period_month      INTEGER NOT NULL,
    threshold_percent INTEGER NOT NULL,
    used_units        BIGINT  NOT NULL,
    included_units    INTEGER NOT NULL,
    triggered_at      TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT pk_quota_alerts PRIMARY KEY (id),
    -- Each threshold alerts once per tenant per period, even under concurrent consumers.
    CONSTRAINT uk_quota_alerts_org_period_threshold
        UNIQUE (organization_id, period_year, period_month, threshold_percent),
    CONSTRAINT fk_quota_alerts_organization FOREIGN KEY (organization_id) REFERENCES organizations (id)
);
